{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 48,
   "metadata": {},
   "outputs": [],
   "source": [
    "### generates layer 1 ###\n",
    "\n",
    "dwg = svgwrite.Drawing('spritz_rect_layer_1.svg', profile='tiny')\n",
    "hk = 0.1 #half kerf width\n",
    "x_span = [-10.85-4, 289.85+4]\n",
    "y_span = [-1.825-2, 85.725+2]\n",
    "outer_width = x_span[1] - x_span[0] + 2*hk\n",
    "outer_height = y_span[1] - y_span[0] + 2*hk\n",
    "\n",
    "# outer cut outline\n",
    "dwg.add(dwg.rect((x_span[0]-hk, y_span[0]-hk), (outer_width, outer_height), #slightly bigger for kerf\n",
    "    stroke = 'black',\n",
    "    fill = \"none\",\n",
    "    rx = 2+hk,\n",
    "    ry = 2+hk,\n",
    "    stroke_width=0.01)\n",
    ")\n",
    "\n",
    "# mounting hole cuts\n",
    "with open('Spritzgeback_hole_coordinates.csv', newline='') as csvfile:\n",
    "    for line in csv.reader(csvfile):\n",
    "        x = float(line[0])\n",
    "        y = float(line[1])\n",
    "        dwg.add(dwg.circle(center=(x,y),\n",
    "            r=3.96/2-hk-0.02, #subtract for kerf plus little extra\n",
    "            stroke='black',\n",
    "            fill='none',\n",
    "            stroke_width=0.01)\n",
    "        )\n",
    "\n",
    "# cutout for USB\n",
    "with open('Spritzgeback_USBcutout1_coordinates.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.01))\n",
    "\n",
    "    \n",
    "dwg.save()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {},
   "outputs": [],
   "source": [
    "### generates layer 2 ###\n",
    "\n",
    "dwg = svgwrite.Drawing('spritz_rect_layer_2.svg', profile='tiny')\n",
    "hk = 0.1 #half kerf width\n",
    "\n",
    "# outer cut outline\n",
    "dwg.add(dwg.rect((x_span[0]-hk, y_span[0]-hk), (outer_width, outer_height), #slightly bigger for kerf\n",
    "    stroke = 'black',\n",
    "    fill = \"none\",\n",
    "    rx = 2+hk,\n",
    "    ry = 2+hk,\n",
    "    stroke_width=0.01)\n",
    ")\n",
    "# mounting hole cuts\n",
    "with open('Spritzgeback_hole_coordinates.csv', newline='') as csvfile:\n",
    "    for line in csv.reader(csvfile):\n",
    "        x = float(line[0])\n",
    "        y = float(line[1])\n",
    "        dwg.add(dwg.circle(center=(x,y),\n",
    "            r=3.96/2-hk-0.02, #subtract for kerf plus little extra\n",
    "            stroke='black',\n",
    "            fill='none',\n",
    "            stroke_width=0.01)\n",
    "        )\n",
    "\n",
    "# cutout for USB\n",
    "with open('Spritzgeback_USBcutout2_coordinates.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.01))\n",
    "\n",
    "\n",
    "# box cutouts for switches\n",
    "with open('Spritzgeback_switch_coordinates.csv', newline='') as csvfile:\n",
    "    switch_centers = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        switch_centers.append((float(line[0]), float(line[1])))\n",
    "\n",
    "for center in switch_centers:\n",
    "    x = center[0]\n",
    "    y = center[1]\n",
    "    points = [(x-7, y-7), (x+7, y-7), (x+7, y+7), (x-7, y+7), (x-7, y-7)]\n",
    "    #msp.add_lwpolyline(points)\n",
    "    dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.01))\n",
    "    \n",
    "# cutout for arduino\n",
    "with open('Spritzgeback_cutout1_coordinates.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='blue', fill='none',stroke_width=0.01))\n",
    "\n",
    "with open('Spritzgeback_cutout2_coordinates.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='blue', fill='none',stroke_width=0.01))\n",
    "\n",
    "with open('Spritzgeback_cutout3_coordinates.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='blue', fill='none',stroke_width=0.01))\n",
    "\n",
    "dwg.save()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {},
   "outputs": [],
   "source": [
    "### generates layer 3 ###\n",
    "\n",
    "dwg = svgwrite.Drawing('spritz_rect_layer_3.svg', profile='tiny')\n",
    "hk = 0.1 #half kerf width\n",
    "\n",
    "# outer cut outline\n",
    "dwg.add(dwg.rect((x_span[0]-hk, y_span[0]-hk), (outer_width, outer_height), #slightly bigger for kerf\n",
    "    stroke = 'black',\n",
    "    fill = \"none\",\n",
    "    rx = 2+hk,\n",
    "    ry = 2+hk,\n",
    "    stroke_width=0.01)\n",
    ")\n",
    "\n",
    "# inner cut outline\n",
    "dwg.add(dwg.rect((-10.85+hk, -1.825+hk), (300.7-2*hk, 87.55-2*hk), #slightly bigger for kerf\n",
    "    stroke = 'black',\n",
    "    fill = \"none\",\n",
    "    rx = 2+hk,\n",
    "    ry = 2+hk,\n",
    "    stroke_width=0.01)\n",
    ")\n",
    "\n",
    "# mounting hole cuts\n",
    "with open('Spritzgeback_hole_coordinates.csv', newline='') as csvfile:\n",
    "    for line in csv.reader(csvfile):\n",
    "        x = float(line[0])\n",
    "        y = float(line[1])\n",
    "        dwg.add(dwg.circle(center=(x,y),\n",
    "            r=3.96/2-hk-0.02, #subtract for kerf plus little extra\n",
    "            stroke='black',\n",
    "            fill='none',\n",
    "            stroke_width=0.01)\n",
    "        )\n",
    "\n",
    "dwg.save()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "metadata": {},
   "outputs": [],
   "source": [
    "### generates layer 4 ###\n",
    "\n",
    "dwg = svgwrite.Drawing('spritz_rect_layer_4.svg', profile='tiny')\n",
    "hk = 0.1 #half kerf width\n",
    "\n",
    "# outer cut outline\n",
    "dwg.add(dwg.rect((x_span[0]-hk, y_span[0]-hk), (outer_width, outer_height), #slightly bigger for kerf\n",
    "    stroke = 'black',\n",
    "    fill = \"none\",\n",
    "    rx = 2+hk,\n",
    "    ry = 2+hk,\n",
    "    stroke_width=0.01)\n",
    ")\n",
    "\n",
    "# reset hole cutouts\n",
    "with open('Spritzgeback_reset_coordinates.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='blue', fill='none',stroke_width=0.01))\n",
    "\n",
    "# mounting hole cuts\n",
    "with open('Spritzgeback_hole_coordinates.csv', newline='') as csvfile:\n",
    "    for line in csv.reader(csvfile):\n",
    "        x = float(line[0])\n",
    "        y = float(line[1])\n",
    "        dwg.add(dwg.circle(center=(x,y),\n",
    "            r=3.96/2-hk-0.02, #subtract for kerf plus little extra\n",
    "            stroke='black',\n",
    "            fill='none',\n",
    "            stroke_width=0.01)\n",
    "        )\n",
    "\n",
    "# box cutouts for switches\n",
    "with open('Spritzgeback_switch_coordinates.csv', newline='') as csvfile:\n",
    "    switch_centers = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        switch_centers.append((float(line[0]), float(line[1])))\n",
    "\n",
    "for center in switch_centers:\n",
    "    x = center[0]\n",
    "    y = center[1]\n",
    "    dist = 6.9-hk\n",
    "    points = [(x-dist, y-dist), (x+dist, y-dist), (x+dist, y+dist), (x-dist, y+dist), (x-dist, y-dist)]\n",
    "    #msp.add_lwpolyline(points)\n",
    "    dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.01))\n",
    "    \n",
    "dwg.save()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "metadata": {},
   "outputs": [],
   "source": [
    "### generates CAD svg ###\n",
    "\n",
    "import svgwrite\n",
    "from svgwrite import cm, mm\n",
    "import csv\n",
    "\n",
    "dwg = svgwrite.Drawing('spritz_rect_CAD.svg', profile='tiny')\n",
    "hk = 0 #half kerf width\n",
    "x_span = [-10.85-4, 289.85+4]\n",
    "y_span = [-1.825-2, 85.725+2]\n",
    "outer_width = x_span[1] - x_span[0] + 2*hk\n",
    "outer_height = y_span[1] - y_span[0] + 2*hk\n",
    "\n",
    "# outer cut outline\n",
    "dwg.add(dwg.rect((x_span[0]-hk, y_span[0]-hk), (outer_width, outer_height), #slightly bigger for kerf\n",
    "    stroke = 'black',\n",
    "    fill = \"none\",\n",
    "    rx = 2+hk,\n",
    "    ry = 2+hk,\n",
    "    stroke_width=0.01)\n",
    ")\n",
    "\n",
    "# mounting hole cuts\n",
    "with open('Spritzgeback_hole_coordinates.csv', newline='') as csvfile:\n",
    "    for line in csv.reader(csvfile):\n",
    "        x = float(line[0])\n",
    "        y = float(line[1])\n",
    "        dwg.add(dwg.circle(center=(x,y),\n",
    "            r=3.96/2-hk-0.02, #subtract for kerf plus little extra\n",
    "            stroke='black',\n",
    "            fill='none',\n",
    "            stroke_width=0.01)\n",
    "        )\n",
    "\n",
    "## cutout for USB (layer 1)\n",
    "with open('Spritzgeback_USBcutout1_coordinates.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.01))\n",
    "        \n",
    "# cutout for USB (layer 2)\n",
    "with open('Spritzgeback_USBcutout2_coordinates.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.01))\n",
    "\n",
    "\n",
    "# box cutouts for switches\n",
    "with open('Spritzgeback_switch_coordinates.csv', newline='') as csvfile:\n",
    "    switch_centers = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        switch_centers.append((float(line[0]), float(line[1])))\n",
    "\n",
    "for center in switch_centers:\n",
    "    x = center[0]\n",
    "    y = center[1]\n",
    "    points = [(x-7, y-7), (x+7, y-7), (x+7, y+7), (x-7, y+7), (x-7, y-7)]\n",
    "    #msp.add_lwpolyline(points)\n",
    "    dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.01))\n",
    "    \n",
    "# cutout for arduino\n",
    "with open('Spritzgeback_cutout1_coordinates.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='blue', fill='none',stroke_width=0.01))\n",
    "\n",
    "with open('Spritzgeback_cutout2_coordinates.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='blue', fill='none',stroke_width=0.01))\n",
    "\n",
    "with open('Spritzgeback_cutout3_coordinates.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='blue', fill='none',stroke_width=0.01))\n",
    "\n",
    "# inner cut outline\n",
    "dwg.add(dwg.rect((-10.85+hk, -1.825+hk), (300.7-2*hk, 87.55-2*hk), #slightly bigger for kerf\n",
    "    stroke = 'black',\n",
    "    fill = \"none\",\n",
    "    rx = 2+hk,\n",
    "    ry = 2+hk,\n",
    "    stroke_width=0.01)\n",
    ")\n",
    "    \n",
    "dwg.save()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
