{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {},
   "outputs": [],
   "source": [
    "### generates layer 1 ###\n",
    "\n",
    "import svgwrite\n",
    "from svgwrite import cm, mm\n",
    "import csv\n",
    "\n",
    "dwg = svgwrite.Drawing('spritz_hotswap_layer_1.svg', size=('313mm', '96mm'), viewBox=('0 0 313 96'))\n",
    "hk = 0.1 #half kerf width\n",
    "x_span = [-17, 296]\n",
    "y_span = [-6.075, 89.925]\n",
    "outer_width = (x_span[1] - x_span[0] + 2*hk)\n",
    "outer_height = (y_span[1] - y_span[0] + 2*hk)\n",
    "\n",
    "# outer cut outline\n",
    "dwg.add(dwg.rect((x_span[0]-hk, y_span[0]-hk), (outer_width, outer_height), #slightly bigger for kerf\n",
    "    stroke = 'black',\n",
    "    fill = \"none\",\n",
    "    rx = 2+hk,\n",
    "    ry = 2+hk,\n",
    "    stroke_width=0.2)\n",
    ")\n",
    "\n",
    "# mounting hole cuts\n",
    "with open('Spritzgeback_hole_coordinates.csv', newline='') as csvfile:\n",
    "    for line in csv.reader(csvfile):\n",
    "        x = float(line[0])\n",
    "        y = float(line[1])\n",
    "        dwg.add(dwg.circle(center=(x,y),\n",
    "            r=(3.96/2-hk-0.02), #subtract for kerf plus little extra\n",
    "            stroke='black',\n",
    "            fill='none',\n",
    "            stroke_width=0.2)\n",
    "        )\n",
    "\n",
    "# cutout for USB\n",
    "with open('Spritzgeback_USBcutout1_coordinates.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "    \n",
    "dwg.save()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {},
   "outputs": [],
   "source": [
    "### generates layer 2 ###\n",
    "\n",
    "import svgwrite\n",
    "from svgwrite import cm, mm\n",
    "import csv\n",
    "\n",
    "dwg = svgwrite.Drawing('spritz_hotswap_layer_2.svg', size=('313mm', '96mm'), viewBox=('0 0 313 96'))\n",
    "hk = 0.1 #half kerf width\n",
    "\n",
    "# outer cut outline\n",
    "dwg.add(dwg.rect((x_span[0]-hk, y_span[0]-hk), (outer_width, outer_height), #slightly bigger for kerf\n",
    "    stroke = 'black',\n",
    "    fill = \"none\",\n",
    "    rx = 2+hk,\n",
    "    ry = 2+hk,\n",
    "    stroke_width=0.2)\n",
    ")\n",
    "\n",
    "# inner cut outline\n",
    "dwg.add(dwg.rect((-7.85+hk, -0.025+hk), (294.7-2*hk, 83.95-2*hk), #slightly bigger for kerf\n",
    "    stroke = 'black',\n",
    "    fill = \"none\",\n",
    "    rx = 2+hk,\n",
    "    ry = 2+hk,\n",
    "    stroke_width=0.2)\n",
    ")\n",
    "\n",
    "# cutout for clearance with sockets in bottom row\n",
    "with open('Spritzgeback_bottom_socket_cutouts.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "# mounting hole cuts (inner)\n",
    "with open('Spritzgeback_hole_coordinates.csv', newline='') as csvfile:\n",
    "    for line in csv.reader(csvfile):\n",
    "        x = float(line[0])\n",
    "        y = float(line[1])\n",
    "        dwg.add(dwg.circle(center=(x,y),\n",
    "            r=3.96/2-hk-0.02, #subtract for kerf plus little extra\n",
    "            stroke='black',\n",
    "            fill='none',\n",
    "            stroke_width=0.2)\n",
    "        )\n",
    "        \n",
    "# mounting hole cuts (outer)\n",
    "with open('Spritzgeback_hole_coordinates.csv', newline='') as csvfile:\n",
    "    for line in csv.reader(csvfile):\n",
    "        x = float(line[0])\n",
    "        y = float(line[1])\n",
    "        dwg.add(dwg.circle(center=(x,y),\n",
    "            r=3.96/2+2-hk-0.02, #subtract for kerf plus little extra\n",
    "            stroke='black',\n",
    "            fill='none',\n",
    "            stroke_width=0.2)\n",
    "        )\n",
    "\n",
    "# cutout for USB\n",
    "with open('Spritzgeback_USBcutout_layer2_inner.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "with open('Spritzgeback_USBcutout_layer2_outer.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "\n",
    "# cutout for hotswap sockets and arduino\n",
    "with open('Spritzgeback_layer2_cutout1.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "with open('Spritzgeback_layer2_cutout2.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "with open('Spritzgeback_layer2_cutout3.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "with open('Spritzgeback_layer2_cutout4.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "with open('Spritzgeback_layer2_cutout5.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "with open('Spritzgeback_layer2_cutout5.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "with open('Spritzgeback_layer2_cutout6.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "dwg.save()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "metadata": {},
   "outputs": [],
   "source": [
    "### generates layer 3 ###\n",
    "\n",
    "import svgwrite\n",
    "from svgwrite import cm, mm\n",
    "import csv\n",
    "\n",
    "dwg = svgwrite.Drawing('spritz_hotswap_layer_3.svg', size=('313mm', '96mm'), viewBox=('0 0 313 96'))\n",
    "hk = 0.1 #half kerf width\n",
    "\n",
    "# outer cut outline\n",
    "dwg.add(dwg.rect((x_span[0]-hk, y_span[0]-hk), (outer_width, outer_height), #slightly bigger for kerf\n",
    "    stroke = 'black',\n",
    "    fill = \"none\",\n",
    "    rx = 2+hk,\n",
    "    ry = 2+hk,\n",
    "    stroke_width=0.2)\n",
    ")\n",
    "\n",
    "# inner cut outline\n",
    "dwg.add(dwg.rect((-11.55+hk, -2.525+hk), (302.1-2*hk, 88.95-2*hk),\n",
    "    stroke = 'black',\n",
    "    fill = \"none\",\n",
    "    rx = 2+hk,\n",
    "    ry = 2+hk,\n",
    "    stroke_width=0.2)\n",
    ")\n",
    "\n",
    "# mounting hole cuts\n",
    "with open('Spritzgeback_hole_coordinates.csv', newline='') as csvfile:\n",
    "    for line in csv.reader(csvfile):\n",
    "        x = float(line[0])\n",
    "        y = float(line[1])\n",
    "        dwg.add(dwg.circle(center=(x,y),\n",
    "            r=4.22/2-hk,\n",
    "            stroke='black',\n",
    "            fill='none',\n",
    "            stroke_width=0.2)\n",
    "        )\n",
    "\n",
    "dwg.save()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "metadata": {},
   "outputs": [],
   "source": [
    "### generates layer 4 ###\n",
    "\n",
    "import svgwrite\n",
    "from svgwrite import cm, mm\n",
    "import csv\n",
    "\n",
    "dwg = svgwrite.Drawing('spritz_hotswap_layer_4.svg', size=('313mm', '96mm'), viewBox=('0 0 313 96'))\n",
    "hk = 0.1 #half kerf width\n",
    "\n",
    "# outer cut outline\n",
    "dwg.add(dwg.rect((x_span[0]-hk, y_span[0]-hk), (outer_width, outer_height), #slightly bigger for kerf\n",
    "    stroke = 'black',\n",
    "    fill = \"none\",\n",
    "    rx = 2+hk,\n",
    "    ry = 2+hk,\n",
    "    stroke_width=0.2)\n",
    ")\n",
    "\n",
    "# mounting hole cuts\n",
    "with open('Spritzgeback_hole_coordinates.csv', newline='') as csvfile:\n",
    "    for line in csv.reader(csvfile):\n",
    "        x = float(line[0])\n",
    "        y = float(line[1])\n",
    "        dwg.add(dwg.circle(center=(x,y),\n",
    "            r=4.22/2-hk,\n",
    "            stroke='black',\n",
    "            fill='none',\n",
    "            stroke_width=0.2)\n",
    "        )\n",
    "\n",
    "# box cutouts for switches\n",
    "with open('Spritzgeback_switch_coordinates.csv', newline='') as csvfile:\n",
    "    switch_centers = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        switch_centers.append((float(line[0]), float(line[1])))\n",
    "\n",
    "for center in switch_centers:\n",
    "    x = center[0]\n",
    "    y = center[1]\n",
    "    dist = 6.9-hk\n",
    "    points = [(x-dist, y-dist), (x+dist, y-dist), (x+dist, y+dist), (x-dist, y+dist), (x-dist, y-dist)]\n",
    "    #msp.add_lwpolyline(points)\n",
    "    dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "    \n",
    "dwg.save()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "metadata": {},
   "outputs": [],
   "source": [
    "### generates CAD svg ###\n",
    "\n",
    "import svgwrite\n",
    "from svgwrite import cm, mm\n",
    "import csv\n",
    "\n",
    "dwg = svgwrite.Drawing('spritz_hotswap_CAD.svg', size=('313mm', '96mm'), viewBox=('0 0 313 96'))\n",
    "hk = 0 #half kerf width\n",
    "x_span = [-16, 295]\n",
    "y_span = [-5.075, 88.925]\n",
    "outer_width = x_span[1] - x_span[0] + 2*hk\n",
    "outer_height = y_span[1] - y_span[0] + 2*hk\n",
    "\n",
    "# outer cut outline\n",
    "dwg.add(dwg.rect((x_span[0]-hk, y_span[0]-hk), (outer_width, outer_height), #slightly bigger for kerf\n",
    "    stroke = 'black',\n",
    "    fill = \"none\",\n",
    "    rx = 2+hk,\n",
    "    ry = 2+hk,\n",
    "    stroke_width=0.2)\n",
    ")\n",
    "\n",
    "# mounting hole cuts\n",
    "with open('Spritzgeback_hole_coordinates.csv', newline='') as csvfile:\n",
    "    for line in csv.reader(csvfile):\n",
    "        x = float(line[0])\n",
    "        y = float(line[1])\n",
    "        dwg.add(dwg.circle(center=(x,y),\n",
    "            r=3.96/2-hk, #subtract for kerf plus little extra\n",
    "            stroke='black',\n",
    "            fill='none',\n",
    "            stroke_width=0.2)\n",
    "        )\n",
    "\n",
    "## cutout for USB (layer 1)\n",
    "with open('Spritzgeback_USBcutout1_coordinates.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "# layer 2 inner cut outline\n",
    "dwg.add(dwg.rect((-7.85+hk, -0.025+hk), (294.7-2*hk, 83.95-2*hk), #slightly bigger for kerf\n",
    "    stroke = 'black',\n",
    "    fill = \"none\",\n",
    "    rx = 2+hk,\n",
    "    ry = 2+hk,\n",
    "    stroke_width=0.2)\n",
    ")\n",
    "\n",
    "# cutout for clearance with sockets in bottom row\n",
    "with open('Spritzgeback_bottom_socket_cutouts.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "# mounting hole cuts (inner)\n",
    "with open('Spritzgeback_hole_coordinates.csv', newline='') as csvfile:\n",
    "    for line in csv.reader(csvfile):\n",
    "        x = float(line[0])\n",
    "        y = float(line[1])\n",
    "        dwg.add(dwg.circle(center=(x,y),\n",
    "            r=3.96/2-hk-0.02, #subtract for kerf plus little extra\n",
    "            stroke='black',\n",
    "            fill='none',\n",
    "            stroke_width=0.2)\n",
    "        )\n",
    "        \n",
    "# mounting hole cuts (outer)\n",
    "with open('Spritzgeback_hole_coordinates.csv', newline='') as csvfile:\n",
    "    for line in csv.reader(csvfile):\n",
    "        x = float(line[0])\n",
    "        y = float(line[1])\n",
    "        dwg.add(dwg.circle(center=(x,y),\n",
    "            r=3.96/2+2-hk-0.02, #subtract for kerf plus little extra\n",
    "            stroke='black',\n",
    "            fill='none',\n",
    "            stroke_width=0.2)\n",
    "        )\n",
    "\n",
    "# cutout for USB\n",
    "with open('Spritzgeback_USBcutout_layer2_inner.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "with open('Spritzgeback_USBcutout_layer2_outer.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "\n",
    "# cutout for hotswap sockets and arduino\n",
    "with open('Spritzgeback_layer2_cutout1.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "with open('Spritzgeback_layer2_cutout2.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "with open('Spritzgeback_layer2_cutout3.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "with open('Spritzgeback_layer2_cutout4.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "with open('Spritzgeback_layer2_cutout5.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "with open('Spritzgeback_layer2_cutout5.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "with open('Spritzgeback_layer2_cutout6.csv', newline='') as csvfile:\n",
    "    points = []    \n",
    "    for line in csv.reader(csvfile):\n",
    "        points.append((float(line[0]), float(line[1])))\n",
    "dwg.add(dwg.polyline(points,\n",
    "    stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "# inner cut outline layer 3\n",
    "dwg.add(dwg.rect((-11.55+hk, -2.525+hk), (302.1-2*hk, 88.95-2*hk),\n",
    "    stroke = 'black',\n",
    "    fill = \"none\",\n",
    "    rx = 2+hk,\n",
    "    ry = 2+hk,\n",
    "    stroke_width=0.2)\n",
    ")\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "    \n",
    "dwg.save()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "# make fidget\n",
    "\n",
    "dwg = svgwrite.Drawing('fidget_1p5.svg', profile='tiny')\n",
    "\n",
    "\n",
    "import itertools\n",
    "from itertools import product \n",
    "\n",
    "width = 1.5\n",
    "\n",
    "rows = 6-1\n",
    "cols = 5-1\n",
    "row_centers = [(10+20*i) for i in range(0,rows+1)]\n",
    "col_centers = [(10+20*i) for i in range(0,cols+1)]\n",
    "\n",
    "centers = [(x,y) for x in row_centers for y in col_centers]\n",
    "\n",
    "count = 0\n",
    "\n",
    "for center in centers:\n",
    "    x = center[0]\n",
    "    y = center[1]\n",
    "    points = [(x-6.8, y-6.8), (x+6.8, y-6.8), (x+6.8, y+6.8), (x-6.8, y+6.8), (x-6.8, y-6.8)]\n",
    "    dwg.add(dwg.polyline(points,                     \n",
    "        stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "    points = [(x-10, y-10), (x+10, y-10), (x+10, y+10), (x-10, y+10), (x-10, y-10)]\n",
    "    dwg.add(dwg.polyline(points,                     \n",
    "        stroke='black', fill='none',stroke_width=0.2))\n",
    "\n",
    "    if count%2 == 0:\n",
    "        points = [(x-10-width, y-3), (x-10-width, y+3), (x+10+width, y+3), (x+10+width, y-3), (x-10-width, y-3)]\n",
    "        dwg.add(dwg.polyline(points,                     \n",
    "            stroke='black', fill='none',stroke_width=0.2))\n",
    "    else: \n",
    "        points = [(x-3, y-10-width), (x+3, y-10-width), (x+3, y+10+width), (x-3, y+10+width), (x-3, y-10-width)]\n",
    "        dwg.add(dwg.polyline(points,                     \n",
    "            stroke='black', fill='none',stroke_width=0.2))\n",
    "        \n",
    "    count = count + 1\n",
    "dwg.save()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
